### ISSUE TITLE
which files should be copied?

### ISSUE THREAD

**Issue by grawk** [aredridel/copy-browser-modules#3]
If I am trying to copy the browser module for requirejs, I'm doing the following:

In my main project's package.json:

```
"browserPackage": {
    "overrides": {
      "requirejs": {
        "main": "require"
      }
    }
  }
```

In my `copy-browser-modules` config (via grunt task):

```
{
      root: process.cwd(),
      dest: 'public/components',
      basePath: 'public'
}
```

Then, in "public/components" there ends up being essentially the entire contents of `node_modules/requirejs` instead of only the `require.js` file.

I may simply be misunderstanding the functionality of this module..

**Comment by aredridel** [comment]
Is there a reason you need to limit it?

**Comment by aredridel** [comment]
(in general, this tool is npm-like: just copy the stuff in the package. You could add a files section to that override a la npm, but why strip it?)

**Comment by grawk** [comment]
Assuming the npm module's amd module is a single file, with no external dependencies, copying out more than that is adding extraneous files into the destination directory. Maybe _that_ assumption is the problem?

**Comment by aredridel** [comment]
I think so. I see no reason to elide things -- I treated the package as a whole package, not meant to aim for single files unless someone wants to do work. Just as if we only wanted one file out of an npm package we'd look at them funny. Just use what you need, and don't worry about the parts of the package you don't use

**Comment by grawk** [comment]
OK. I just wanted to be sure the behavior I was seeing was intended. That makes sense.

**Comment by ohpyupi** [comment]
Wouldn't this be a good feature if a developer can pick which file they want to ship to their code base? Currently, what I am experiencing is since `copy-browser-module` ship all files including test files, I need to handle include/exclude logics in my code base. I think It will be definitely a good feature if we can copy files selectively.
