### ISSUE TITLE
Issues using this with modules using keyword "browser"

### ISSUE THREAD

**Issue by grawk** [aredridel/copy-browser-modules#5]
I've tried using this module in a project which also uses browserify. It looks like the logic here is capturing packages which don't actually have a browser module due to this logic:

```
var browser = overrides[c.package.name] || c.package.browserPackage || (c.package.keywords && ~c.package.keywords.indexOf("browser"));
if (!browser) return;
```

Because browserify has "browser" as a keyword, and browserify shows up multiply in `node_modules`, the "Overlapping packages found" error is triggered.

If the keywords terms are removed from the logic, the running of `copy-browser-modules` works as expected.

**Comment by aredridel** [comment]
Ah too aggressive. Sad! I was hoping that'd work out. I'd love an equally light weight way to signal that a module is friendly enough.

**Comment by grawk** [comment]
Thanks!
