### ISSUE TITLE
Throwing error while using with npm >= 5.10.0

### ISSUE THREAD

**Issue by kumarrishav** [aredridel/copy-browser-modules#7]
Error
```
[33mWarning: ENOENT: no such file or directory, open '/workspace/appName-ci-8789_pullrequest/node_modules/fsevents/package.json' Use --force to continue.[39m"" seems to show that the file/ directory cannot be found.
```

**Comment by aredridel** [comment]
What are you doing that triggers this error?

**Comment by kumarrishav** [comment]
I am using grunt-copy-browser-module and using it as a grunt task. Till npm 5.5.1, its working fine.

**Comment by kumarrishav** [comment]
```
module.exports=function dustjs(grunt) {
grunt.loadNpmTasks('grunt-copy-browser-modules');

return {
build: {
root: process.cwd(),
dest: 'public/js/components',
basePath: 'public/js'
}
}
}
```

**Comment by aredridel** [comment]
Reverting to the previous version of npm works?

**Comment by kumarrishav** [comment]
yeah. Unable to figure out the issue causing this so far.

**Comment by kumarrishav** [comment]
Not sure what is breaking in npm version > 5.5.0

**Comment by aredridel** [comment]
Hmm. And that's the complete output? That's not output of this module, but it might be of the grunt wrapper. (I've not used the grunt wrapper in quite some time)

**Comment by aredridel** [comment]
When you change npm versions, what else changes? (Are these wholly fresh installed node_modules? Or ones other versions of npm have touched?)

**Comment by kumarrishav** [comment]
This is the error.
```
4mRunning "copy-browser-modules:build" (copy-browser-modules) task[24m
07:41:17 [33mWarning: ENOENT: no such file or directory, open '/workspace/appName-ci-2093/node_modules/fsevents/package.json' Use --force to continue.[39m
07:41:17 
07:41:17 [31mAborted due to warnings.[39m
```

Yeah, wholly fresh installed node_modules. Same works fine with npm 5.5.1. So,  i guess, its not because of other modules?? 

Also, i was unable to find the grunt-copy-browser-module github repo. It's giving 404

**Comment by aredridel** [comment]
Shucks! Not sure what happened to that repo.

Does that package.json in fact not exist?

I'm curious how you ended up with a package installed without one. That module's a bit wacky, but something seems off there.

**Comment by aredridel** [comment]
I just published a copy-browser-modules 5.0.0 and grunt-copy-browser-modules 7.0.1. I'd love to know if that fixes it. It uses a new read-package-tree with a bunch of fixes since the version I was using.

**Comment by kumarrishav** [comment]
just verified. It's happening with all the release after npm@5.5.1 i.e its failing with even npm@5.6.0

https://github.com/npm/npm/releases/tag/v5.6.0
one update in this version is copy-concurrently. not sure if its related?

**Comment by kumarrishav** [comment]
let me test with copy-browser-modules 5.0.0 and grunt-copy-browser-modules 7.0.1

**Comment by kumarrishav** [comment]
Thanks @aredridel . Got it working now. Was it because of read-package-tree module? https://github.com/npm/npm/commit/5f2bf4222004117eb38c44ace961bd15a779fd66 . You are the saviour.

**Comment by aredridel** [comment]
Not sure, but considering that's the module that the module reading logic was imported from, I suspect so! thanks for the kick in the pants to update this module!
