### ISSUE TITLE
The task fails if "newgat" and "dustjs-helper" are required together

### ISSUE THREAD

**Issue by ohpyupi** [aredridel/copy-browser-modules#8]
I have two packages `newgat` and `dustjs-helper` required for my front-end app. However, `copy-browser-modules` throws an error if I require both of them together. It looks like the problem is since `dustjs-helper` is a dependency to `newgat`, when I require `dustjs-helper` to be copied as a browser module as well, it throws an error, saying `Warning: Overlapping packages found: dustjs-helpers `.

I think the root cause is that this module does not provide a support for npm-like tree structure for npm modules. But I still do need both packages on my project. Is there any way to avoid the error and get those packages copied nicely using the `copy-browser-modules`?

![Screen Shot 2020-01-06 at 10 54 28 AM](https://user-images.githubusercontent.com/17169119/71840839-eedbab00-3072-11ea-852f-2491b1c89884.png)

https://github.com/aredridel/grunt-put-packages-in-requirejs-config/issues/1

**Comment by ohpyupi** [comment]
Okay. Found the reason. It is because `newgat` was not in the common.js format.

**Comment by aredridel** [comment]
Aha!
